const burmeseFood = [
    { id: 1, name: "Mohinga (မုန့်ဟင်းခါး)", price: 1200 },
    { id: 2, name: "Laphet Thoke (လက်ဖက်သုပ်)", price: 1500 },
    { id: 3, name: "Shan Noodles (ရှမ်းချောင်း)", price: 1500 },
    { id: 4, name: "Ohn No Khao Swè (အုန်းနို့ခေါက်ဆွဲ)", price: 1800 },
    { id: 5, name: "Nga Htamin (ငါးထမင်း)", price: 1200 },
    { id: 6, name: "Burmese Curry (ဟင်းလျာ)", price: 2000 },
    { id: 7, name: "Kyay Oh (ကြာအိုး)", price: 1500 },
    { id: 8, name: "Kaukswe Thoke (ခေါက်ဆွဲသုပ်)", price: 1400 },
    { id: 9, name: "Htamin Jin (ထမင်းကြာဇံ)", price: 1300 },
    { id: 10, name: "Tofu Nway (ပဲတီ tofu)", price: 800 },
    { id: 11, name: "Yah Htamin (ရေထမင်း)", price: 1200 },
    { id: 12, name: "Nga Pi Yay (ငါးပီရည်)", price: 1000 },
    { id: 13, name: "Kyauk Kyaw (ကျောက်ချော)", price: 700 },
    { id: 14, name: "Htote Si (ထိုးဆီး)", price: 800 },
    { id: 15, name: "Pancake Mont (မုန့်ကိတ်)", price: 900 },
    { id: 16, name: "Shan Rice (ရှမ်းထမင်း)", price: 1500 },
    { id: 17, name: "Chicken Curry (ကြက်ဟင်းလျာ)", price: 2000 },
    { id: 18, name: "Pork Curry (ဝက်ဟင်းလျာ)", price: 2000 },
    { id: 19, name: "Fried Rice (ကြော်ထမင်း)", price: 1200 },
    { id: 20, name: "Vegetable Soup (ဟင်းသုပ်ဟင်းရွက်)", price: 1000 },
    { id: 21, name: "Bein Mont (ဘိန်းမုန့်)", price: 800 },
    { id: 22, name: "Mont Lin Ma Yar (မုန့်လင်းမယား)", price: 700 },
    { id: 23, name: "A Kyaw (အာကြော်)", price: 500 },
    { id: 24, name: "Samusa (စမူဆာ)", price: 600 },
    { id: 25, name: "Pe Byouk (ပဲပြုတ်)", price: 700 },
    { id: 26, name: "Ngapi Ye (ငါးပီရည်လိမ်)", price: 800 },
    { id: 27, name: "Seik Mont (ဆိပ်မုန့်)", price: 900 },
    { id: 28, name: "Shwe Yin Aye (ရွှေယင်အေး) – dessert snack", price: 1200 },
    { id: 29, name: "Mandalay Mee Shay (မန္တလေးမီးရှယ်)", price: 1500 },
    { id: 30, name: "Htamin Gyaw (ထမင်းကြော်)", price: 1200 },
    { id: 31, name: "Lahpet Yay (လက်ဖက်ရည်) – Burmese tea", price: 800 },
    { id: 32, name: "Shwe Yin Aye (ရွှေယင်အေး) – Coconut dessert drink", price: 1200 },
    { id: 33, name: "Toddy Palm Juice (သစ်တော်ရည်) – Palm sap drink", price: 1000 },
    { id: 34, name: "Coffee Laphet Yay (ကော်ဖီလက်ဖက်ရည်) – Burmese coffee", price: 1200 },
    { id: 35, name: "Milk Tea (နို့ရည်လက်ဖက်) – Sweet Burmese milk tea", price: 1000 },
    { id: 36, name: "Coconut Juice (အုန်းရည်)", price: 900 },
    { id: 37, name: "Lime Juice (သံပရာရည်)", price: 800 },
    { id: 38, name: "Sugarcane Juice (သကြားသီးရည်)", price: 900 },
    { id: 39, name: "Palm Wine (အိပ်မက်ရည်)", price: 1500 },
    { id: 40, name: "Butter Tea (လက်ဖက်နို့ကြမ်းရည်)", price: 1200 },
    { id: 41, name: "Fish Curry (ငါးဟင်းလျာ)", price: 2000 },
    { id: 42, name: "Prawn Curry (ပုစွန်ဟင်းလျာ)", price: 2500 },
    { id: 43, name: "Egg Curry (ဥဟင်းလျာ)", price: 1800 },
    { id: 44, name: "Tofu Curry (ပဲတီဟင်းလျာ)", price: 1500 },
    { id: 45, name: "Tomato Salad (ခရမ်းချဉ်သုပ်)", price: 1200 },
    { id: 46, name: "Cabbage Salad (မုန်လာဥသုပ်)", price: 1000 },
    { id: 47, name: "Green Bean Salad (ပဲစိမ်းသုပ်)", price: 1000 },
    { id: 48, name: "Pickled Mango (ငှက်ပျောသုပ်)", price: 1200 },
    { id: 49, name: "Pumpkin Curry (ပေါင်းဟင်းလျာ)", price: 1500 },
    { id: 50, name: "Bitter Gourd Curry (ပဲအရိုင်းဟင်းလျာ)", price: 1500 },
    { id: 51, name: "Nan Gyi Thoke (နန်းကြီးသုပ်)", price: 1400 },
    { id: 52, name: "Pork Sausage (ဝက်သားဆိုဆယ့်)", price: 1200 },
    { id: 53, name: "Fried Tofu (ပဲတီကြော်)", price: 700 },
    { id: 54, name: "Puff Pastry (မုန့်ပူဖ်)", price: 900 },
    { id: 55, name: "Sweet Potato Cake (ကလေးနီမုန့်)", price: 800 },
    { id: 56, name: "Sticky Rice Cake (ထမင်းဆန်မုန့်)", price: 900 },
    { id: 57, name: "Sesame Balls (ကြာဇံပေါင်လေး)", price: 700 },
    { id: 58, name: "Coconut Jelly (အုန်းချော)", price: 800 },
    { id: 59, name: "Rice Crackers (ထမင်းလုံးကြော်)", price: 600 },
    { id: 60, name: "Fried Banana (ငှက်ပျောကြော်)", price: 700 }
];

export default burmeseFood;
